---
ansible_host: 3.142.182.238
ansible_host_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMi0FpLCBApi7E6gzQxjC717BC0nvpav+77Dcg1BeOSN
ansible_user: ubuntu
vlayer_prover_host: 127.0.0.1
vlayer_prover_port: 3000
vlayer_alchemy_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30653339336433326133363333376638626339643363353332353238633630643730393233666564
  3161643066643238623134613435323666353664373866660a356566656437356237323461393134
  65653366653138363666376338383937336431373564323731333062653534383461636438383732
  3834383930633437640a343839623938666362343331343361316234393264643065333763343731
  32383431303831333565643864393230656531366134376337316633633138636365383165343932
  3763623233653161396139633032356631356433343539383832
vlayer_prover_rpc_urls:
 - "11155111:https://eth-sepolia.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "11155420:https://opt-sepolia.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "1:https://eth-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "8453:https://base-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "10:https://opt-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "84532:https://base-sepolia.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "80002:https://polygon-amoy.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "421614:https://arb-sepolia.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "300:https://zksync-sepolia.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "8453:https://base-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "42161:https://arb-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "42170:https://arbnova-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "137:https://polygon-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "324:https://zksync-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "747:https://flow-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "545:https://flow-testnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "534352:https://scroll-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "534351:https://scroll-sepolia.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "5000:https://mantle-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "59144:https://linea-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "59141:https://linea-sepolia.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "100:https://gnosis-mainnet.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 - "10200:https://gnosis-chiado.g.alchemy.com/v2/{{ vlayer_alchemy_api_key }}"
 # https://docs.bitkubchain.org/rpc-service/rpc
 # The rate limit of RPC endpoint on Mainnet and Testnet is 2K/1min.
 - "96:https://rpc.bitkubchain.io"
 - "25925:https://rpc-testnet.bitkubchain.io"
 # https://docs.kinto.xyz/kinto-the-safe-l2/building-on-kinto/tools/node-rpc
 - "7887:https://rpc.kinto-rpc.com"
 # https://docs.celo.org/network
 - "42220:https://forno.celo.org"
 # https://docs.zircuit.com/dev-tools/rpc-endpoints
 - "48900:https://zircuit1-mainnet.p2pify.com"
 - "48899:https://zircuit1-testnet.p2pify.com"
 # https://docs.fhenix.zone/getting-started
 - "8008135:https://api.helium.fhenix.zone"
vlayer_proof_type: groth16
vlayer_bonsai_api_url: "https://api.bonsai.xyz/"
vlayer_bonsai_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34633535313637623033303635633161363539643365616232656132306431663763303833623332
  3536353163643137373936616636653136323366383663390a666534356339303539623939633861
  38643038333561373337323839303630643731653131383661653562343262326235666464636465
  6536343764363663630a316265666433313766653466313137363839666339303962383934373436
  36643331306466336166316162323133633637633136623130666563643030306364306330353731
  3536323333376261393638383364616437316136393263373966
vlayer_prover_gas_meter_url: "https://dashboard.vlayer.xyz/api/webhooks/prover"
vlayer_prover_gas_meter_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31396562656134383833636463386566376232323636633734323837343464636139303532656663
  6230633632623363343866363866633936316465363334390a346633336339363562396135383961
  31363239666135646438366364626335373061633466646332653032623564366162653634343830
  6361393633376332300a386531383066653235393766333232623136646335373265323939336163
  33646361663465363932646333366464366663613132303739356564353466616133666233396633
  66316461656164363263333731663365393962373739366534326562343436656434343166306633
  32623238383032663439343164663332643461353339393964643438383432316634346333333230
  64326132366630306266626539626538396233623034313630326362653932316435633963353536
  62353932643337323737666234353765623363643531646533336435333564326636366436336531
  35633263303637613536333463643966336565313263396131623132306632333631313165376534
  333634303764653162643233336133656661
