[package]
name = "call_server"
version = "0.1.0"
edition = "2021"

[dependencies]
call_engine = { workspace = true }
tower-http = { workspace = true, features=["cors"] }
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
hex = { workspace = true }
axum-jrpc = { workspace = true }
call_host = { workspace = true }
alloy-chains = { workspace = true }
web_proof = { workspace = true }
server_utils = { workspace = true }
chain = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
lazy_static = { workspace = true }
web_proof = { workspace = true, features = ["fixtures"] }
ethers = { workspace = true }
assert-json-diff = "2.0.2"
