[package]
name = "block_trie"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
bytes = { workspace = true }
risc0-zkp = { workspace = true }
block_header = { workspace = true }
mpt = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true, features = ["arrayvec"] }
risc0-zkvm = { workspace = true }
bincode = { workspace = true }

[lints]
workspace = true
