[package]
name = "block_trie"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true, features = ["arrayvec"] }
block_header = { workspace = true }
bytes = { workspace = true }
mpt = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
traits = { workspace = true }

[dev-dependencies]
chain_test_utils = { workspace = true }

[lints]
workspace = true
