[package]
name = "chain_server"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros"] }
axum-jrpc = { workspace = true }
bincode = "1.3.3"
chain_common = { workspace = true }
chain_db = { workspace = true }
common = { workspace = true }
dotenvy = { workspace = true }
lazy_static = { workspace = true }
mpt = { workspace = true }
parking_lot = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
server_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["ansi"] }
u64_range = { workspace = true }

[lints]
workspace = true
