[package]
name = "chain_server"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros"] }
axum-jrpc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
server_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
chain_host = { workspace = true}
risc0-zkvm = { workspace = true }
risc0-zkp = { workspace = true }
bincode = "1.3.3"
mpt = { workspace = true }
lazy_static.workspace = true

[lints]
workspace = true
