[package]
name = "chain_guest"
version = "0.1.0"
edition = "2021"

[dependencies]
block_trie = { workspace = true }
block_header = { workspace = true }
serde = { workspace = true }
mpt = { workspace = true }
risc0-zkp = { workspace = true }
alloy-primitives = { workspace = true }

[lints]
workspace = true
