[package]
name = "chain_db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chain_engine = { workspace = true }
thiserror = { workspace = true }
libmdbx = "0.5.2"
mpt = { workspace = true }
alloy-rlp = { workspace = true }
alloy-primitives = { workspace = true }
nybbles = { workspace = true }

[dev-dependencies]
rand = "0.8.5"
tempfile = { workspace = true }

[lints]
workspace = true
