[package]
name = "chain_db"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
anyhow = { workspace = true }
block_trie = { workspace = true }
bytes = { workspace = true }
chain_guest_wrapper = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
key_value = { workspace = true }
mpt = { workspace = true }
nybbles = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
risc0-zkvm = { workspace = true }
risc0-zkp = { workspace = true }
bincode = { workspace = true }
traits = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
