[package]
name = "zkvm-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
block_header = { workspace = true, features = ["test-utils"] }
block_trie = { workspace = true }
call_precompiles = { workspace = true }
common = { workspace = true, default-features = false }
derive-new = { workspace = true }
derive_more = { workspace = true }

email_proof = { workspace = true }
mpt = { workspace = true }
risc0-zkvm = { workspace = true, optional = true }
rsa = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }

[features]
risc0 = ["dep:risc0-zkvm"]
sp1 = []

[lints]
workspace = true
