[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chain_host = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["ansi"] }

[lints]
workspace = true
