[[bin]]
name = "vlayer"
path = "src/main.rs"

[package]
name = "cli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
call_guest_wrapper = { workspace = true }
call_server = { workspace = true }
test_runner = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "string"] }
flate2 = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
alloy-primitives = { workspace = true, features = ["rlp"] }
risc0-zkp = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }

[dev-dependencies]
regex = "1.10.6"

[build-dependencies]
vergen = { workspace = true, features = ["build", "git", "gitcl"] }

[lints]
workspace = true
