[package]
name = "host_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { workspace = true, features = ["prove"] }
anyhow = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
