[package]
name = "web_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
tlsn-core = { workspace = true }
p256 = { workspace = true }
pkcs8 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true} 
thiserror = { workspace = true }

[features]
fixtures = []
