[package]
name = "call_precompiles"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
cfg-if = { workspace = true }
derive_more = { workspace = true }
email_proof = { workspace = true }
regex = { workspace = true }
revm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
urlpattern = { workspace = true }
web_proof = { workspace = true }

[lints]
workspace = true
