[package]
name = "call_host"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-ethereum-contracts = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm = { workspace = true }
host_utils = { workspace = true }
call_engine = { workspace = true }
call_guest_wrapper = { workspace = true }
mpt = { workspace = true }
alloy-chains = { workspace = true }
alloy-primitives = { workspace = true, features = ["rlp", "serde"] }
ethers-providers = { workspace = true }
ethers-core = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
revm = { workspace = true, features = ["serde", "std"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
auto_impl = { workspace = true }
dotenv = { workspace = true }
chain = { workspace = true }

[dev-dependencies]
alloy-sol-types = { workspace = true }
test-log = { workspace = true }
anyhow = { workspace = true }
ctor = { workspace = true }
