[package]
name = "server_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros"] }
axum-jrpc = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
http-body-util = { workspace = true }
mime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace"] }
tower-request-id = { workspace = true }
tracing = { workspace = true }
host_utils = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
mockito = "1.5.0"

[lints]
workspace = true
