[package]
name = "chain_host"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
block_trie = { workspace = true }
chain_db = { workspace = true }
chain_guest = { workspace = true }
chain_guest_wrapper = { workspace = true }
chain_test_utils = { workspace = true }
derivative = { workspace = true }
derive-new ={ workspace = true }
dotenvy = { workspace = true }
ethers = { workspace = true }
futures = { workspace = true }
host_utils = { workspace = true }
lazy_static = { workspace = true }
provider = { workspace = true }
range = { workspace = true }
risc0-zkvm = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }

[dev-dependencies]
alloy-rlp = { workspace = true, features = ["arrayvec"] }
serde_json = { workspace = true }

[lints]
workspace = true
