[package]
name = "chain_host"
version = "0.1.0"
edition = "2021"

[dependencies]
host_utils = { workspace = true }
alloy-primitives = { workspace = true }
risc0-zkvm = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
chain_engine = { workspace = true }
thiserror = { workspace = true }
chain_guest_wrapper = { workspace = true }
mpt = { workspace = true }
chain_db = { workspace = true }
ethers = { workspace = true }
provider = { workspace = true }

[lints]
workspace = true
