[package]
name = "chain_host"
version = "0.1.0"
edition = "2021"

[dependencies]
host_utils = { workspace = true }
bytes = { workspace = true }
alloy-primitives = { workspace = true }
risc0-zkvm = { workspace = true }
risc0-zkp = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
block_trie = { workspace = true }
thiserror = { workspace = true }
chain_guest = { workspace = true }
chain_guest_wrapper = { workspace = true }
mpt = { workspace = true }
kv = { workspace = true }
ethers = { workspace = true }
provider = { workspace = true }
derivative = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
lazy_static = { workspace = true }
bincode = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
alloy-rlp = { workspace = true, features = ["arrayvec"] }

[lints]
workspace = true
