
services:
  websockify:
    image: jwnmulder/websockify
    platform: linux/amd64
    ports:
      - "55688:80"
    command: "80 swapi.dev:443"
  notary-server:
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.5
    ports:
      - "7047:7047"
    volumes:
      - ./notary-config:/root/.notary-server/config
  anvil:
    build:
      context: ../..
      dockerfile: docker/web-proof/anvil/Dockerfile
    platform: linux/amd64
    ports:
      - "8545:8545"
  vlayer:
    build:
      context: ../..
      dockerfile: docker/web-proof/vlayer/Dockerfile
    ports:
      - "3000:3000"
