name: End-to-end integration test

on:
  schedule:
    - cron: '0 23 * * 1-5' # Mon-Fri at 23:00 UTC
  push:
    paths:
      - "rust/**"
      - "examples/**"
      - "bash/**"
      - ".github/workflows/**"

jobs:
  e2e-test:
    runs-on: aws-linux-small
    steps:
      - uses: oven-sh/setup-bun@v2
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            rust
            rust/guest_wrapper/risc0_guest

      - uses: cargo-bins/cargo-binstall@main

      - name: Install risc0 toolchain
        run: |
          cargo binstall -y cargo-risczero --force
          cargo risczero install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559 # 2024-06-02

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.3
        with:
          version: "17.0.5"

      - name: Build vlayer
        working-directory: rust
        run: cargo build --package cli

      - name: Run e2e test
        env:
          PROVING_MODE: 'prod'
          BONSAI_API_URL: ${{ vars.BONSAI_API_URL }}
          BONSAI_API_KEY: ${{ secrets.BONSAI_API_KEY }}
          VLAYER_TMP_DIR: ./artifacts
        run: bash/e2e-test.sh

      # Teardown
      - name: Display Logs
        if: always()
        run: |
          for log_file in $(find ./artifacts/logs -type f); do
            echo "=== Contents of $log_file ==="
            cat "$log_file"
            echo "============================="
          done
