name: Forge test

on:
  push:
    paths:
      - 'contracts/**'
      - 'examples/**'
      - '.github/workflows/**'
    branches:
      - '**'
  merge_group:

env:
  FOUNDRY_PROFILE: ci

jobs:
  forge-test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: aws-linux-small
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-626221f5ef44b4af950a08e09bd714650d9eb77d # 2024-08-02

      - name: Mock ImageId.sol
        run: ./bash/mock-imageid.sh

      - name: Run Forge build
        working-directory: ./contracts
        run: |
          forge --version
          forge build --sizes

      - name: Run Forge tests
        working-directory: ./contracts
        run: |
          forge test -vvv
      - name: Run Forge formatter
        run: |
          forge fmt ./examples ./contracts --check
