name: Lint Solidity
on: 
  pull_request:
    paths:
      - 'examples/**'
      - 'contracts/**'
  merge_group:
  push:
    branches:
      - main
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  sol-lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install TypeScript prerequisites
        uses: ./.github/actions/ts-prerequisites
      - name: Mock ImageId.sol
        run: ./bash/mock-imageid.sh
      - name: Run install bun 
        working-directory: contracts
        run: bun install --frozen-lockfile
      - name: lint:solidity
        working-directory: contracts
        run: bun run lint:solidity
      - name: lint Solidity examples
        run: ./bash/lint-solidity-examples.sh