name: Lint contracts
on:
  pull_request:
    paths:
      - "contracts/**"
      - ".github/workflows/lint_contracts.yaml"
      - ".github/actions/contracts-prerequisites"
      - ".github/actions/ts-prerequisites"
  merge_group:
  push:
    branches:
      - main
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-contracts:
    name: Lint contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TypeScript prerequisites
        uses: ./.github/actions/ts-prerequisites
      - name: Install contracts prerequisites
        uses: ./.github/actions/contracts-prerequisites

      - name: Mock ImageId.sol
        run: ./bash/mock-imageid.sh
      - name: Install solhint
        working-directory: contracts
        run: bun install --frozen-lockfile
      - name: Contracts lint:solidity
        working-directory: contracts
        run: |
          bun run lint:solidity
      - name: lint Solidity examples
        run: ./bash/lint-solidity-examples.sh
