name: SDK Test

on:
  push:
    paths:
      - "packages/sdk/**"
      - ".github/workflows/**"
    branches:
      - "**"
  merge_group:
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  sdk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: packages/sdk
        run: bun install
      - name: Run SDK tests
        working-directory: packages/sdk
        run: bun test
