name: Test

on:
  push:
    paths:
      - "rust-toolchain.toml"
      - "rust/**"
      - "examples/**"
      - ".github/workflows/**"
    branches:
      - "**"
  merge_group:

jobs:
  rust-test:
    runs-on: aws-linux-small

    steps:
      - uses: cargo-bins/cargo-binstall@main

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            rust
            rust/call/guest_wrapper/risc0_guest

      - name: Install risc0 installer
        run: cargo binstall -y cargo-risczero@1.0.5 --force

      - name: Install risc0 toolchain
        run: cargo risczero install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-626221f5ef44b4af950a08e09bd714650d9eb77d # 2024-08-02

      - name: Check clang and LLVM version
        env:
          EXPECTED_LLVM_VERSION: "18.1"
        run: bash/check_llvm_clang.sh

      - name: Run workspace rust tests
        working-directory: rust
        run: |
          cargo test --workspace --locked
        env:
          RUST_LOG: info
          RISC0_DEV_MODE: 1
