name: Test

on:
  push:
    paths:
      - "rust-toolchain.toml"
      - "rust/**"
      - "examples/**"
      - "packages/vlayer/**"
      - ".github/workflows/**"
    branches:
      - "**"
  merge_group:

jobs:
  rust-test:
    runs-on: aws-linux-small

    steps:
      - uses: cargo-bins/cargo-binstall@main

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            rust
            rust/services/call/guest_wrapper/risc0_guest
            rust/services/chain/guest_wrapper/risc0_guest

      - name: Install risc0 installer
        run: cargo binstall -y cargo-risczero@1.0.5 --force

      - name: Install risc0 toolchain
        run: cargo risczero install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-d75318c9c7a1c6af5404fe96f63ca890dcdd588d # 2024-09-05
      - name: Check clang and LLVM version
        env:
          EXPECTED_LLVM_VERSION: "18.1"
        run: bash/check_llvm_clang.sh

      - name: Run workspace rust tests
        working-directory: rust
        run: |
          cargo test --workspace --locked
        env:
          RUST_LOG: info
          RISC0_DEV_MODE: 1
  ts-test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: packages/vlayer/sdk
        run: bun install
      - name: Run SDK tests
        working-directory: packages/vlayer/sdk
        run: bun test
