name: E2E test of example web apps on devnet

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      relevant-changes: ${{ steps.filter.outputs.relevant-changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            relevant-changes:
              - 'rust-toolchain.toml'
              - 'rust/**'
              - 'examples/**'
              - 'packages/**'
              - 'bash/run-services.sh'
              - 'bash/e2e-web-apps-test.sh'
              - '.github/workflows/test_e2e_web_apps_devnet.yaml'
              - 'contracts/**'

  test-e2e-web-apps-simple:
    name: E2E web apps test against devnet (simple)
    needs: changes
    runs-on: aws-linux-medium
    if: github.event_name == 'push' || needs.changes.outputs.relevant-changes == 'true'
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment and run e2e tests
        uses: ./.github/actions/test-e2e-web-apps-devnet
        with:
          example: "simple"
          playwright_test_x_com_auth_token: ${{ secrets.PLAYWRIGHT_TEST_X_COM_AUTH_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PLAYWRIGHT_REPORT_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}

  test-e2e-web-apps-devnet-simple-web-proof:
    name: Run setup and e2e tests (simple-web-proof)
    needs: changes
    runs-on: aws-linux-medium
    if: needs.changes.outputs.relevant-changes == 'true'
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment and run e2e tests
        uses: ./.github/actions/test-e2e-web-apps-devnet
        with:
          example: "simple-web-proof"
          playwright_test_x_com_auth_token: ${{ secrets.PLAYWRIGHT_TEST_X_COM_AUTH_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PLAYWRIGHT_REPORT_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}

  test-e2e-web-apps-devnet-simple-email-proof:
    name: Run setup and e2e tests (simple-email-proof)
    needs: changes
    runs-on: aws-linux-medium
    if: needs.changes.outputs.relevant-changes == 'true'
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment and run e2e tests
        uses: ./.github/actions/test-e2e-web-apps-devnet
        with:
          example: "simple-email-proof"
          playwright_test_x_com_auth_token: ${{ secrets.PLAYWRIGHT_TEST_X_COM_AUTH_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PLAYWRIGHT_REPORT_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}

  test-e2e-web-apps-devnet-simple-teleport:
    name: Run setup and e2e tests (simple-teleport)
    needs: changes
    runs-on: aws-linux-medium
    if: needs.changes.outputs.relevant-changes == 'true'
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment and run e2e tests
        uses: ./.github/actions/test-e2e-web-apps-devnet
        with:
          example: "simple-teleport"
          playwright_test_x_com_auth_token: ${{ secrets.PLAYWRIGHT_TEST_X_COM_AUTH_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PLAYWRIGHT_REPORT_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}

  test-e2e-web-apps-devnet-simple-time-travel:
    name: Run setup and e2e tests (simple-time-travel)
    needs: changes
    runs-on: aws-linux-medium
    if: needs.changes.outputs.relevant-changes == 'true'
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment and run e2e tests
        uses: ./.github/actions/test-e2e-web-apps-devnet
        with:
          example: "simple-time-travel"
          playwright_test_x_com_auth_token: ${{ secrets.PLAYWRIGHT_TEST_X_COM_AUTH_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PLAYWRIGHT_REPORT_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
