name: Lint TS examples and sdk
on: 
  pull_request:
    paths:
      - 'examples/**'
      - 'packages/**'
  merge_group:
  push:
    branches:
      - main
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Install TypeScript prerequisites
      uses: ./.github/actions/ts-prerequisites
    # mocking is need for contract build to pass
    - name: Mock ImageId.sol
      run: ./bash/mock-imageid.sh 
    # contracts need to be built to run the linter
    - name: Run Forge build
      working-directory: ./contracts
      run: |
        forge soldeer install
        forge build --sizes
    - name: Build abi types 
      run: ./bash/build_ts_types.sh
    - name: Run ESLint
      run: bash/lint-ts.sh
